### ISSUE TITLE
about MobileMeAuthToken

### ISSUE THREAD

**Issue by samfriend** [manwhoami/Poof#1]
Sorry for the dump question, but how to generate a pair of id/MobileMeAuthToken ?

thx

**Comment by manwhoami** [comment]
# Great question!

**Do you know** the Apple ID / password? If you do, I have updated poof to print the DSID / MobileMeAuthToken to the screen after you login with your Apple ID / password.

**Do you not know** the password / Apple ID? 

If you have a Mac / PC / computer with iCloud logged in (via iCloud software), then you can use "Elcomsoft Token Extractor" made by Elcomsoft to give you the token. It is free (no endorsement, just a great product) and requires no authentication.

If you only have an iOS device with iCloud logged in, you can install a Certificate Authority on your phone, and proxy your internet to a computer with the private keys of the Certificate Authority. The DSID/Token will be embed in the Authorization header of an iCloud request that your phone makes, encoded in base64.
